// Governed copy for the V3 assessment player (spec §12, §40). Plain language;
// never implies a score while the assessment is active.
export const PLAYER_COPY = {
  notAvailable: 'This assessment is not available',
  notStartedTitle: 'This assessment has not started yet',
  notStartedBody: 'Open it from Assessments to read the briefing and begin.',
  accessEnded: 'Access to this assessment has ended',
  scenarioMissing: 'Its content is no longer available, so it cannot be shown. Nothing has been substituted.',
  reportPending: 'Your report will appear in Assessments when it is ready.',
  personalVisibility: 'This is a personal assessment. Only you can see the result unless you choose to share it.',
  sponsoredVisibility: (sponsor) => `${sponsor} can see the result of this sponsored assessment. Your personal Prism results stay private.`,
  loadFailed: 'Your assessment could not be loaded',
  offlineTitle: 'You appear to be offline',
  offlineBody: 'Your latest saved work is safe. The assessment will load when your connection is back.',
  notSentRetry: 'It did not reach Prism. Your answer is safe here — retry when you are ready.',
  notSentFinal: 'It could not be accepted. Edit your answer and send it again, or finish the assessment.',
  notSentOffline: 'You appear to be offline. Your answer is safe here and will be sent when you reconnect.',
  pendingAfterRefresh: 'This answer may not have been sent before the page reloaded. Retry to make sure it arrives — it is never counted twice.',
  timeUpTitle: 'Time is up',
  timeUp: 'The time for this assessment has ended. Finish to submit your work.',
  draftNotSubmitted: 'This draft was not submitted. It stays here for your reference and will not be sent.',
  alreadyComplete: 'This assessment has already been completed.',
  unsavedBeforeFinish: 'Some work is not saved yet. Wait for “All work saved”, then finish.',
  notSubmitted: 'Your assessment could not be submitted.',
  completeTitle: 'Assessment complete',
  completeBody: 'Your answers are submitted. Your report shows what was observed, and says where there was not enough evidence.',
  scoringTitle: 'Your answers are being reviewed',
  scoringBody: 'This can take a few minutes. You can leave this page; your report will appear in Assessments when it is ready.',
  savedReviewContinuing: (n) => `Your work is saved (${n} ${n === 1 ? 'response' : 'responses'} recorded). The review is continuing; you can leave this page.`,
  technicalFailedBody: 'We could not complete the review yet. Your saved work is kept. Try again, or contact support with the reference below.',
  statusRefreshFailed: 'We could not refresh the review status. The last saved status is shown.',
  scoringFailedTitle: 'Review did not finish',
  scoringFailedBody: 'The review did not finish, so no completed report is available yet. Try again or contact support.',
  largeScreenTitle: 'This assessment works best on a larger screen',
  largeScreenBody: 'It includes working documents such as tables and planning tools. A laptop or tablet is strongly recommended.',
}
