// Governed copy for Student Report V3 (spec §14, §36.3, §40). Plain language,
// no scores, no readiness or hiring language, no percentages.
export const REPORT_COPY = {
  title: 'Your report',
  sponsorTitle: 'Student report',
  sharedTitle: 'Shared Prism report',
  tabs: { summary: 'Your Prism', capabilities: 'Capabilities', evidence: 'Evidence', development: 'Development', methodology: 'Methodology' },
  // First screen (P5.2): statement -> map -> moments -> next practice -> details.
  mapTitle: 'Capability Map',
  mapIntro: 'Each row shows the band the evidence supports and, separately, how much evidence there was. The bands are ordered categories, not a scale or a score.',
  mapBands: { EARLY: 'Early evidence', DEVELOPING: 'Developing', DEMONSTRATED: 'Demonstrated', STRONG: 'Strongly demonstrated' },
  mapNotMeasured: 'Not yet measured',
  mapUnderReview: 'Under review',
  mapEvidence: { SUFFICIENT: 'Sufficient', PROVISIONAL: 'Provisional', HUMAN_REVIEW_REQUIRED: 'Under review', INSUFFICIENT_EVIDENCE: 'Not enough evidence' },
  mapOpen: 'Open details for',
  mapNoneDescribed: 'No capability has enough evidence to be placed on the map yet. That is a statement about the evidence from this assessment, not about you.',
  momentsTitle: 'Moments that mattered',
  momentsIntro: 'What you did, where it happened and what it showed. Quotes are your exact words.',
  momentsIntroOther: 'What the student did, where it happened and what it showed. Quotes are the student\u2019s exact words.',
  momentsNone: 'No moment from this assessment could be verified against your own words, so none is shown.',
  momentBounded: 'One observed moment, not a level',
  seeMoment: 'See the moment',
  practiseThis: 'Practise this',
  nextTitle: 'Next useful practice',
  nextNone: 'No next practice is suggested from this assessment yet. Suggestions appear only where the evidence supports them.',
  nextWhy: 'Why this',
  versionsTitle: 'Version history',
  versionsIntro: 'Every published version of this report is kept. A correction creates a new version with its reason; nothing is rewritten.',
  versionsNone: 'No version has been published yet.',
  versionReasons: { INITIAL: 'First publication', RE_EVALUATION: 'Re-evaluation of the evidence', CORRECTION: 'Correction after review', REVIEW_CORRECTION: 'Corrected after a review' },
  reviewPending: 'An interpretation review is pending',
  reviewPendingBody: 'A person is looking at what you pointed out. This report stays as published until they decide; any change appears as a new version.',
  correctedTitle: (version, prior) => `Corrected version ${version}${prior ? `, replacing version ${prior}` : ''}`,
  correctedBody: 'A reviewer withheld evidence after your request. This version was published without it; the earlier version is kept unchanged in the history.',
  // P5.6 read-time practice recommendation beside an insight.
  recommendationLabel: 'Practice mission',
  recommendationTitle: 'Where to practise this',
  recommendationUnavailable: 'No reviewed practice is available yet for this.',
  recommendationOff: 'Practice missions are not switched on in this workspace yet.',
  recommendationExhausted: 'Your practice allowance is used up. Finished attempts stay readable.',
  recommendationConsumes: 'Starting uses one practice activity from your allowance.',
  recommendationStretch: 'Optional stretch practice',
  recommendationStretchBody: 'This capability was strongly demonstrated. Practice here is optional, not a correction.',
  reviewOpen: 'Ask for a review',
  reviewTitle: 'Ask for a review of this report',
  reviewIntro: 'A person will look at what you point out. Your report stays as it is while they do; if something changes, it is published as a new version with its reason.',
  reviewCategory: 'What should be looked at',
  reviewCategories: { TRANSCRIPTION: 'How my words were recorded', ATTRIBUTION: 'Whether the words were mine', SCENARIO_FACT: 'A fact about the scenario', INTERPRETATION: 'How a moment was interpreted', OTHER: 'Something else' },
  reviewReason: 'What you would like reviewed',
  reviewReasonHint: 'A few sentences. Refer to a moment or capability where you can.',
  reviewSend: 'Send request',
  reviewSent: 'Your request has been recorded',
  reviewSentBody: 'It is open for a person to review. This page does not promise a timing or an outcome; the version history will show any change.',
  reviewRequests: 'Review requests',
  reviewStates: { OPEN: 'Open', RESOLVED: 'Resolved' },
  summaryIntro: 'Each capability shows what was observed in this assessment and how much evidence there was. Where there was not enough evidence, the report says so instead of guessing.',
  noDescribed: 'This assessment did not produce enough evidence to describe any capability yet. That is a statement about the evidence, not about you.',
  seeEvidence: 'See evidence',
  atAGlance: 'At a glance',
  strengthsTitle: 'Strengths shown by the evidence',
  noStrengths: 'No capability is described as demonstrated yet. Levels appear only where there is enough evidence.',
  focusTitle: 'Where to focus',
  focusTeaser: 'See the development priorities',
  highlightsTitle: 'Evidence highlights',
  highlightsAll: 'See all evidence',
  growthLine: 'Change over time is shown only between assessments approved as comparable.',
  growthLink: 'Open growth',
  technicalDetails: 'Technical details',
  evidenceIntro: 'Every conclusion in this report is linked to something you did in the assessment. Quotes are your exact words.',
  noEvidence: 'There is no evidence to show for this report.',
  developmentIntro: 'Up to three priorities, each based on evidence from this assessment.',
  noPriorities: 'No development priority is based on this assessment yet. Priorities appear only where the evidence supports them.',
  missionsLater: 'Recommended practice missions are not available here yet.',
  reassessmentLater: 'Reassessment windows are not available here yet.',
  methodologyIntro: 'How this report was produced.',
  methodology: [
    'Capabilities are described only when there is enough independent evidence from the assessment.',
    'Level names are provisional while measurement governance finalises them.',
    'Prism does not score personality, intelligence, emotion, voice tone or appearance.',
    'There is no single overall score, and no ranking against other people.',
  ],
  notReadyTitle: 'Your report is not ready yet',
  notReadyBody: 'Reports appear here after the assessment is finished and reviewed.',
  underReviewTitle: 'This report is under review',
  underReviewBody: 'The report is unavailable while the review status is unresolved. Check again or contact support.',
  processingFailedTitle: 'The review did not finish',
  processingFailedBody: 'Your submitted work is saved. The review could not be completed, so no report is shown yet. You can retry from your assessment or contact support.',
  notAvailable: 'This report is not available',
  sharedInvalid: 'This link is not valid or has expired',
  sharedInvalidBody: 'Ask the person who shared it for a new link.',
  visibility: {
    OWNER_ONLY: 'Only you can see this report unless you share it.',
    OWNER_AND_SPONSOR: (sponsor) => `${sponsor} can see this sponsored report. Your personal Prism results stay private.`,
    SHARED_BY_STUDENT: 'The student chose to share this report with your institution.',
  },
  // Charter §9 identity-assurance levels (server lib/sharedConstants ASSURANCE_LEVELS).
  identity: {
    NOT_RECORDED: 'Identity level not recorded',
    L1: 'Identity self-declared',
    L2: 'Identity confirmed by an institution',
    L3: 'Identity verified',
  },
  share: {
    open: 'Share',
    title: 'Share this report',
    recipient: 'Who can see it',
    link: 'Anyone with a private link',
    organization: 'An institution I belong to',
    disclosure: 'What they can see',
    summary: 'Summary only — capability levels and evidence status, no quotes',
    full: 'Full report — including evidence, your quotes and development priorities',
    expiry: 'Share expires after',
    create: 'Create share',
    created: 'Share created',
    linkOnce: 'Copy this link now. For your privacy it is shown only once.',
    copy: 'Copy link',
    copied: 'Copied',
    active: 'Active shares',
    none: 'This report is not shared.',
    revoke: 'Revoke',
    revoked: 'Share revoked',
    manage: 'Manage all shares',
  },
  pdf: 'Download PDF',
}

// Second person for the student; neutral wording for anyone else reading.
const AUDIENCE_COPY = {
  OWNER: {
    noDescribed: 'This assessment did not produce enough evidence to describe any capability yet. That is a statement about the evidence, not about you.',
    evidenceIntro: 'Every conclusion in this report is linked to something you did in the assessment. Quotes are your exact words.',
    fromWorkMaterials: 'From your work materials',
  },
  OTHER: {
    noDescribed: 'This assessment did not produce enough evidence to describe any capability yet. That is a statement about the evidence, not about the student.',
    evidenceIntro: 'Every conclusion in this report is linked to something the student did in the assessment. Quotes are the student\u2019s exact words.',
    fromWorkMaterials: 'From the student\u2019s work materials',
  },
}
export const reportCopyFor = (audience) => (audience === 'OWNER' ? AUDIENCE_COPY.OWNER : AUDIENCE_COPY.OTHER)

export const SHARE_EXPIRY_OPTIONS = [
  { value: '7', label: '7 days' },
  { value: '30', label: '30 days' },
  { value: '90', label: '90 days' },
  { value: '180', label: '180 days (longest)' },
]
